name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker image build . -t apache_web
    - name: deploy Docker image
      run: docker run -d -p 8080:80 apache_web:latest
    - name: Test App in Container
      run: curl -v http://localhost:8080/
